spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mj_webmagic?useUnicode=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.mj.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
